testomatio/reporter

- lib/client.js
- package.json
Added some catch operators to handle failed requests.
Also I highly recommend using `async/await` syntax instead of .then/.catch
> Fix for client errors

- lib/client.js
> Add proper error message

- lib/adapter/mocha.js
I have added "pending" status handler for the mocha adapter.
> [ISSUE-664]: mocha pending status handler.

- README.md
- lib/client.js
- lib/fileUploader.js
- lib/pipe/csv.js
- lib/pipe/github.js
- lib/pipe/gitlab.js
- lib/pipe/testomatio.js
https://github.com/testomatio/reporter/issues/117
> Add debug() calls through the code #117

- Changelog.md
- lib/bin/reportXml.js
- lib/util.js
- lib/xmlReader.js
- package.json
- tests/data/junit_simple.xml
- tests/data/selenide.xml
- tests/util_test.js
- tests/xmlReader_test.js
> added junit improvements

- lib/bin/startTest.js
[ISSUE-232] check -c before opts using
> [ISSUE-232] check -c before opts using

- lib/fileUploader.js
- package.json
S3 FILE uploading fixes:
- Added additional waiting for the file to exist => checkFileExists()
- remove responce.Location instead of out.singleUploadResult.Location
> S3 FILE uploading issues (#246, #253)

- lib/adapter/playwright.js
- lib/data-storage.js
- lib/utils/utils.js
Accidentally missed storage implementation for playwright
> implement Storage for Playwright

- docs/env-variables.md
- lib/data-storage.js
- tests-storage/data-storage.test.js
- tests-storage/logger.test.js
- tests-storage/reporter-functions.test.js
Reverts testomatio/reporter#292
> Revert "Storage filename fix"

- docs/env-variables.md
- lib/data-storage.js
- tests-storage/data-storage.test.js
- tests-storage/logger.test.js
- tests-storage/reporter-functions.test.js
Reverts testomatio/reporter#300
> Revert "Revert "Storage filename fix""

- docs/env-variables.md
- docs/frameworks.md
- docs/pipes/testomatio.md
- lib/adapter/playwright.js
- lib/client.js
https://github.com/testomatio/reporter/issues/239
> exculde tests from report by regex

- lib/pipe/testomatio.js
> Improved error notification on submit

- lib/adapter/playwright.js
https://github.com/testomatio/check-tests/issues/149
> Parse PW tags to get test id

- lib/pipe/csv.js
Playwright + TS -> should be work as expected (issue - https://github.com/testomatio/reporter/issues/337 )
[ISSUE-337] fix report.csv saving if test includes 'FAILED' tests + style adjustments
> [ISSUE-337] fix report.csv saving if test includes 'FAILED' tests

- .github/workflows/linter-and-tests.yml
- lib/bin/reportXml.js
- lib/junit-adapter/csharp.js
- lib/pipe/gitlab.js
- lib/xmlReader.js
- package.json
- tests/data/specflow.xml
- tests/xmlReader_test.js
* big XML files support
* support specflow xml
> Added support for specflow and big files

- lib/pipe/testomatio.js
- package.json
this pr needs to generate testomat report in case of using proxy
> add proxy support for testomatio report

- .github/workflows/linter-and-tests.yml
- lib/adapter/codecept.js
- lib/bin/reportXml.js
- lib/pipe/gitlab.js
- lib/xmlReader.js
- tests/xmlReader_test.js
https://github.com/testomatio/reporter/issues/346
> implemented xml reporting with subsuites in specflow

- lib/bin/startTest.js
`--finish` transformed run to parallel which was not correct
> run --finish should not mark run as parallel

- docs/configuration.md
- docs/pipes/testomatio.md
- lib/pipe/testomatio.js
Requires backend changes to be published to make it work
https://github.com/testomatio/testomatio/issues/4557
> implemented shared timeout config

- docs/functions.md
- lib/adapter/mocha.js
- lib/adapter/webdriver.js
- lib/reporter.js
`reporter.log(text)` or `log(text)`
> logger for wdio; fix reporter exports

- docs/configuration.md
- lib/adapter/codecept.js
https://github.com/testomatio/docler-issues/issues/450
> fixed running codeceptjs retries

- lib/adapter/playwright.js
- lib/client.js
> Playwright: send project name and other project data

- src/bin/reportXml.js
In order to auto-load code from tests
> Guess java tests path at reportXml.js

- lib/xmlReader.js
https://github.com/testomatio/testomatio/issues/4393
> fixed collecting duration for JUnit reports

- lib/xmlReader.js
Minor cleanup in XML reader functionality:
- Removed unnecessary empty line in data processing
- Improved code formatting in `xmlReader.js`
- Cleaned up redundant whitespace in `XmlReader` class
- Small formatting improvements for better code readability
Simple maintenance update with no functional changes.
> fix: Improve XML import functionality and error handling

- lib/utils/utils.js
- tests/data/csharp_tid.xml
- tests/xmlReader_test.js
Fixes https://github.com/testomatio/app/issues/1279
> improved the way tid is parsed
